[package]
name = "rediSQL"
version = "0.4.0"
authors = ["Simone Mosciatti <simone@redbeardlab.tech>"]

[lib]
name = "redis_sql"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.30.0"
cc = {version = "1.0.3", features = ["parallel"]}

[dependencies]
fnv = "1.0.5"
uuid = { version = "0.4", features = ["v4"] }
log = {version = "0.3.8", features = ["release_max_level_warn"]}
env_logger = "0.4.3"
redisql_lib = {path = "./redisql_lib"}
# engine_pro = {path = "./engine_pro", optional = true}

[features]
default = []

# pro = ["engine_pro"]
