
site_name: RediSQL
repo_url: https://github.com/RedBeardLab/rediSQL
google_analytics:
  - UA-116709819-1
  - auto

pages:
  -
    Overview: index.md
  -
    References: references.md
  -
    Pro: pro.md
  -
    Motivations:
      - "Motivations": motivations.md
      - "PRO Motivations": pro_motivations.md
  -
    Blog:
      - 'Analytics': 'blog/analytics.md'
      - 'JSON on Redis using RediSQL, SQL steroids for Redis': 'blog/JaaS.md'
      - 'Double performances of RediSQL going zero copy': 'blog/performances.md'
      - 'Release 0.5.0': 'blog/release_0.5.0.md'
      - 'Release 0.6.0': 'blog/release_0.6.0.md'
